version: '3.7'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: doogie
      MYSQL_DATABASE: entity_practice
    volumes:
      - mysql-data:/var/lib/mysql
      - /Users/Doogie/dg/mysql/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
volumes:
  mysql-data:
